name: Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["✨ enhancement"]
body:
  - type: textarea
      id: description
      attributes:
        label: Description
        description: A clear and concise description of what the bug is.
      validations:
        required: true
  - type: textarea
      id: steps
      attributes:
        label: Steps to Reproduce
        description:  To help us recreate the bug, provide a numbered list of the exact steps taken to trigger the buggy behavior.
        value:  | 
          If you know the steps, follow the below format and provide steps to reproduce

          For example:

          1. Go to <replace your> page.
          1. On top right side, close to the <Account> menu
          1. Some menu are not working properly.
          1. Continue...

          If you don't know exact steps, include any relevant details like:

          - What page you were on...
          - What you were trying to do...
          - What went wrong...
      validations:
        required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
      id: assignee
      attributes:
        label: Do you want to work on this issue?
        multiple: false
        options:
          - "No"
          - "Yes"
        default: 0
      validations:
        required: false